// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const supabase = createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_ANON_KEY // Use service role key for admin access
);

// Test connection
(async () => {
    const { data, error } = await supabase.rpc('now'); // 'now' is a built-in Postgres function
    if (error) {
        console.error("Supabase connection failed:", error.message);
    } else {
        console.log("Supabase connected! Server time:", data);
    }
})();

export { supabase };
