// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();
console.log("SUPABASE_URL:", process.env.SUPABASE_URL);


const supabase = createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_ANON_KEY // Use service role key for admin access
);

export { supabase };
