// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

// Use service role key on backend to bypass RLS for server-side operations
const supabase = createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY
);

// Test connection
(async () => {
    const { data, error } = await supabase
        .from('collections') // Use a table that exists in your DB
        .select('id')
        .limit(1);

    if (error) {
        console.error("Supabase connection failed:", error.message);
    } else {
        console.log("Supabase connected! Sample data:", data);
    }
})();

export { supabase };
